export const links = (model, variables) => [
	{ none: () => true },
	{ dex_protocol_path: 				() => Object.keys(model).some(item => item.includes('.protocol')) },
	{ dex_exchange_path: 				() => Object.keys(model).some(item => item.includes('.exchange.fullName')) },
	{ token_path: 						() => Object.keys(model).some(item => item.includes('.currency.symbol') || item.includes('.currency.address')) },
	{ buy_token_path: 					() => Object.keys(model).some(item => item.includes('.buyCurrency.address') || item.includes('.buyCurrency.address')) },
	{ sell_token_path: 					() => Object.keys(model).some(item => item.includes('.sellCurrency.address') || item.includes('.sellCurrency.address')) },
	{ smart_contract_method_path: 		() => Object.keys(model).some(item => item.includes('.smartContractMethod.signatureHash')) },
	{ smart_contract_event_path: 		() => Object.keys(model).some(item => item.includes('.smartContractEvent.signatureHash')) },
	{ address_path: 					() => Object.keys(model).some(item => item.includes(`${Object.keys(model)[2]}.address.address`)) },
	{ sender_address_path: 				() => Object.keys(model).some(item => item.includes('.sender.address')) },
	{ receiver_address_path: 			() => Object.keys(model).some(item => item.includes('.receiver.address')) },
	{ block_path: 						() => Object.keys(model).some(item => item.includes('.block.height')) },
	{ transaction_path: 				() => Object.keys(model).some(item => item.includes('.hash') || item.includes('.transaction.hash')) },
	{ smart_contract_path: 				() => Object.keys(model).some(item => item.includes('.smartContract.address.address')) },
	{ property_value_path: 				() => Object.keys(model).some(item => item.includes(`${Object.keys(model)[2]}.address.address`) || item.includes('.block.height')) },
	{ token_pair_path: 					() => Object.keys(model).some(item => item.includes('.baseCurrency.address') || item.includes('.quoteCurrency.address')) },
	{ transfer_to_path: 				() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.currency.address') || item.includes('.currency.symbol') )},
	{ transfer_to_path: 				() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.currency.address') || item.includes('.currency.symbol') )},
	{ transfer_token_sender_path: 		() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.sender.address')) },
	{ transfer_token_receiver_path: 	() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.receiver.address')) },
	{ call_count_path: 					() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.smartContract.address.address')) },
	{ call_method_count_path: 			() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.smartContractMethod.signatureHash')) },
	{ event_count_path: 				() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.smartContractEvent.signatureHash')) },
	{ internal_call_method_count_path: 	() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.smartContractMethod.signatureHash')) },
	{ external_call_method_count_path: 	() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes('.smartContractMethod.signatureHash')) },
	{ call_by_caller_count_path: 		() => (variables && 'address' in variables) && Object.keys(model).some(item => item.includes(`${Object.keys(model)[2]}.address.address`)) }
]
